print("Digitare y per una parabola in funzione di x (es. y=ax2+bx+c)")
print("Digitare x per una parabola in funzione di y (es. x=ay2+by+c)\n")

yx= input("Scelta: ")

if yx== "x":
	a= int(input("Inserire il termine a: "))
	b= int(input("Inserire il termine b: "))
	c= int(input("Inserire il termine c: "))
	print("\n")
	delta= pow(b, 2) - (4*a*c)
	print("Il delta dell'equazione inserita: ", delta, "\n")
	xv=- delta/(4*a)
	yv=- b/(2*a)
	print("Le coordinate del vertice sono V(", xv, ";", yv,")\n")
	print("L'asse della parabola è: y=", yv, "\n")
	xf=(1-delta)/(4*a)
	yf=- b/(2*a)
	print("Le coordinate del fuoco sono F(", xf, ";", yf, ")\n")
	direttrice=- (1+delta)/(4*a)
	print("L'equazione della direttrice: x=", direttrice)
elif yx== "y":
	a= int(input("Inserire il termine a: "))
	b= int(input("Inserire il termine b: "))
	c= int(input("Inserire il termine c: "))
	print("\n")
	delta= pow(b, 2) - (4*a*c)
	print("Il delta dell'equazione inserita: ", delta, "\n")
	xv=- b/(2*a)
	yv=- delta/(4*a)
	print("Le coordinate del vertice sono V(", xv, ";", yv,")\n")
	print("L'asse della parabola è: x=", xv, "\n")
	xf=- b/(2*a)
	yf=(1-delta)/(4*a)
	print("Le coordinate del fuoco sono F(", xf, ";", yf, ")\n")
	direttrice=- (1+delta)/(4*a)
	print("L'equazione della direttrice: x=", direttrice)